In [ ]:
import numpy as np

In [ ]:
a=np.random.randint(-5,-1,size=(5,4))

In [ ]:
print(a)
print(a[2:4,1:3])

[[-5 -3 -3 -4]
 [-4 -5 -2 -3]
 [-3 -3 -4 -2]
 [-5 -3 -5 -5]
 [-2 -3 -4 -2]]
[[-3 -4]
 [-3 -5]]


In [ ]:
import math
b=np.zeros((5,7))
#b.shape[1]
#b.shape[0]
#print(b)
#print(b[:0])
mid_row=math.floor(b.shape[0]/2)
mid_col=math.floor(b.shape[1]/2)
print(mid_col)
b[mid_row,:]=1
#print(b)
b[:,mid_col]=1
print(b)

3
[[0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]


In [11]:
a=np.random.randint(-5,-1,size=(5,4))
print(a)
a[:,1]=a[:,1]+2
print(a)
print(a.min())
print(a.max())
print(a[1].mean())

[[-4 -3 -5 -3]
 [-3 -3 -5 -2]
 [-5 -4 -3 -2]
 [-5 -5 -5 -5]
 [-4 -4 -4 -4]]
[[-4 -1 -5 -3]
 [-3 -1 -5 -2]
 [-5 -2 -3 -2]
 [-5 -3 -5 -5]
 [-4 -2 -4 -4]]
-5
-1
-2.75
